"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, fmt } from "@/lib/api";
import ProvBadge from "@/components/Prov";

export default function Ask() {
  const [q, setQ] = useState("");
  const [ex, setEx] = useState<string[]>([]);
  const [res, setRes] = useState<any | null>(null);
  const [busy, setBusy] = useState(false);
  useEffect(() => { api<string[]>("/ask/examples").then((r) => setEx(r.data)); }, []);
  const go = async (text: string) => {
    setQ(text); setBusy(true);
    try { setRes((await api("/ask", { q: text })).data); } finally { setBusy(false); }
  };
  const drillHref = (d: any) => {
    if (!d?.player) return null;
    const p = new URLSearchParams();
    if (d.route) p.set("route", d.route);
    if (d.bowler_family) p.set("bowler_family", d.bowler_family);
    return `/players/${d.player}${p.toString() ? "?" + p : ""}`;
  };
  return (
    <div className="search-hero fade-in" style={{ maxWidth: 760 }}>
      <div className="kicker">Ask Cricket · v0</div>
      <h1 className="big-title" style={{ fontSize: "clamp(34px, 8vw, 60px)" }}>Ask. Every number is a query.</h1>
      <p className="sub">Answers come from fixed analytical templates run against the dataset. No language model writes the numbers. If a question isn&apos;t supported yet, we say so.</p>
      <form onSubmit={(e) => { e.preventDefault(); if (q.trim()) go(q.trim()); }} style={{ display: "flex", gap: 8, marginTop: 16 }}>
        <input className="input" value={q} onChange={(e) => setQ(e.target.value)} placeholder="e.g. Who has dismissed … the most?" aria-label="Ask a question" />
        <button className="btn primary" type="submit" disabled={busy}>{busy ? "…" : "Ask"}</button>
      </form>
      <div className="chips" style={{ marginTop: 12 }}>
        {ex.map((e) => <button key={e} className="chip wrap" onClick={() => go(e)}>{e}</button>)}
      </div>
      {res && (
        <div className="card fade-in" style={{ marginTop: 20 }}>
          {res.status === "ok" ? (
            <>
              <div className="kicker">{res.intent.replace(/_/g, " ")}</div>
              <div style={{ fontSize: 20, fontWeight: 700, lineHeight: 1.35, marginTop: 6 }}>{res.answer}</div>
              {res.caveat && <div className="note">{res.caveat}</div>}
              {res.numbers?.length > 0 && (
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 10, marginTop: 14 }}>
                  {res.numbers.map((n: any, i: number) => (
                    <div key={i} className="hstat" style={{ background: "var(--bg-2)" }}>
                      <div className="v num" style={{ fontSize: 26 }}>{typeof n.value === "number" ? fmt(n.value, Number.isInteger(n.value) ? 0 : 1) : n.value ?? "–"}</div>
                      <div className="l">{n.label}{n.n != null ? ` · n=${n.n}` : ""}</div>
                      <div style={{ marginTop: 4 }}><ProvBadge prov={n.prov} /></div>
                    </div>
                  ))}
                </div>
              )}
              <div style={{ display: "flex", gap: 8, marginTop: 16, flexWrap: "wrap" }}>
                {drillHref(res.drill) && <Link className="btn primary" href={drillHref(res.drill)!}>See it on the player page →</Link>}
              </div>
              <details style={{ marginTop: 14 }}>
                <summary className="mini" style={{ cursor: "pointer" }}>How this was computed</summary>
                <div className="mini" style={{ marginTop: 6 }}>
                  Intent <code>{res.intent}</code> · players {res.entities.map((e: any) => `${e.name} (${e.person_id})`).join(", ")} ·
                  filters <code>{JSON.stringify(res.filters)}</code><br />{res.how_computed}<br />Generated by: {res.generated_by}
                </div>
              </details>
            </>
          ) : (
            <>
              <div style={{ fontWeight: 700 }}>{res.message}</div>
              {res.candidates && <div className="results">{res.candidates.map((c: any) => <Link key={c.person_id} className="res" href={`/players/${c.person_id}`}><span>{c.name}</span><span className="mini">{c.matches} matches</span></Link>)}</div>}
              {res.examples && <div className="chips" style={{ marginTop: 10 }}>{res.examples.map((e: string) => res.examples_are_templates
                ? <span key={e} className="chip wrap unknown">{e}</span>
                : <button key={e} className="chip" onClick={() => go(e)}>{e}</button>)}</div>}
            </>
          )}
        </div>
      )}
    </div>
  );
}
