"""Provenance is a first-class concept: every non-trivial value carries one of these classes.

OBSERVED       directly stated by a source record (e.g. Cricsheet says kind == "bowled").
DERIVED        deterministically computed/classified from observed data (e.g. wicketkeeper inferred
               from stumpings; score-before-ball from the delivery sequence).
RECONSTRUCTED  an approximation drawn from incomplete event data (e.g. a ball path to the keeper
               when no trajectory exists). Only ever used by the scene/graphics layer.
MODELLED       a statistical/ML estimate (e.g. next-ball probabilities).
ILLUSTRATIVE   generic explanation of a concept; never presented as what happened.
"""
from enum import Enum


class Prov(str, Enum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    RECONSTRUCTED = "RECONSTRUCTED"
    MODELLED = "MODELLED"
    ILLUSTRATIVE = "ILLUSTRATIVE"


# Registry of data sources. Every canonical row carries a source_id that must exist here.
SOURCES = {
    "cricsheet": {
        "name": "Cricsheet",
        "url": "https://cricsheet.org",
        "licence": "Register: ODC-By 1.0 (primary-verified on cricsheet.org/register). Match data: no licence statement found on cricsheet.org (site footer: 'All rights reserved'); confirmation requested before publication.",
        "attribution": "Ball-by-ball data and player register from Cricsheet (cricsheet.org). Register under the Open Data Commons Attribution License.",
        "synthetic": False,
    },
    "synthetic_fixture": {
        "name": "Synthetic test fixture",
        "url": None,
        "licence": "Generated by this project for testing. Fictional teams and players.",
        "attribution": "SYNTHETIC TEST DATA — fictional players and matches, not real cricket.",
        "synthetic": True,
    },
    "derived": {
        "name": "cricintel derivation",
        "url": None,
        "licence": "Derived from the upstream source of each input row",
        "attribution": None,
        "synthetic": False,
    },
    "wikidata": {
        "name": "Wikidata",
        "url": "https://www.wikidata.org",
        "licence": "CC0 1.0",
        "attribution": None,
        "synthetic": False,
    },
    "manual_override": {
        "name": "Manual metadata override",
        "url": None,
        "licence": "Project-curated; each row must cite its evidence",
        "attribution": None,
        "synthetic": False,
    },
}
